### ISSUE TITLE
Several API documentation script improvements

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-api#199]
This issue collects all the tasks related to improving the API documentation:

### Fixes
- [ ] Remove underscore from Active Response in API reference (More info: https://github.com/wazuh/wazuh-documentation/issues/573)
- [ ] Unify `curl` command. Use `http://localhost:55000`, without `-k` flag (Default Wazuh API configuration) (More info: https://github.com/wazuh/wazuh-documentation/pull/619)
- [x] Remove unused asterisk characters on API reference (More info: https://github.com/wazuh/wazuh-documentation/issues/264)
- [x] Add warning about custom WPK file API call (More info: https://github.com/wazuh/wazuh-documentation/commit/3464636a72a0cab7711b5ee69765a11282ae8484)
- [x] Fix typo in API reference (More info: https://github.com/wazuh/wazuh-documentation/pull/651)

### Improvements
- [ ] Update API docs script for new Config on-demand table format (More info: https://documentation.wazuh.com/current/user-manual/api/reference.html#get-active-configuration)
- [ ] Improve documentation for DELETE/agents (Needs further details) (More info: https://github.com/wazuh/wazuh-documentation/issues/278)
- [ ] Some API requests doesn't have all the parameters properly documented or the description is not clear (Needs further defails) (More info: https://github.com/wazuh/wazuh-documentation/issues/269)
- [ ] Add list of expected fields in output for each API request in API reference (Needs further defails) (More info: https://github.com/wazuh/wazuh-documentation/issues/268)
- [ ] 'select' parameter isn't documented in some API reference endpoints (Needs further defails) (More info: https://github.com/wazuh/wazuh-documentation/issues/262)
- [ ] Add description of output fields (More info: https://github.com/wazuh/wazuh-documentation/issues/650) (Example: http://api.ctan.es/doc/)

**Comment by mgmacias95** [comment]
Hello @JuanjiJG,

This issue will be fixed with the migration to OpenAPI we're doing for Wazuh 4.0. It won't be fixed for 3.x releases.

Best regards,
Marta

**Comment by davidjiglesias** [comment]
Deprecated in Wazuh v4.0.0
