### ISSUE TITLE
[Development] Wazuh manager 4.0 uninstall doesn't stop the Wazuh API. 

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-api#494]
Hello team

  We noticed that the Wazuh API is not stopped after a Wazuh manager 4.0.0 uninstall. 

In a Wazuh manager 4.0.0 fresh install we can see the following processes:

```
[root@6eb2bbd5d3fb /]# ps -xa | grep ossec
   1074 ?        Sl     0:00 /var/ossec/bin/ossec-authd
   1090 ?        Sl     0:00 /var/ossec/bin/wazuh-db
   1114 ?        Sl     0:00 /var/ossec/bin/ossec-execd
   1126 ?        Sl     0:00 /var/ossec/bin/ossec-analysisd
   1221 ?        SNl    0:04 /var/ossec/bin/ossec-syscheckd
   1233 ?        Sl     0:00 /var/ossec/bin/ossec-remoted
   1266 ?        Sl     0:00 /var/ossec/bin/ossec-logcollector
   1305 ?        Sl     0:00 /var/ossec/bin/ossec-monitord
   1315 ?        Sl     0:00 /var/ossec/bin/wazuh-modulesd
   1763 ?        Sl     0:08 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py restart
   1822 pts/0    S+     0:00 grep --color=auto ossec
```
We identify `1763` as the wazuh API embedded process. 

In a 3.13.1 Wazuh manager and Wazuh API fresh installation:
```
     97 ?        Sl     0:00 /var/ossec/bin/ossec-authd
    117 ?        Sl     0:00 /var/ossec/bin/wazuh-db
    145 ?        Sl     0:00 /var/ossec/bin/ossec-execd
    161 ?        Sl     0:00 /var/ossec/bin/ossec-analysisd
    260 ?        SNl    0:05 /var/ossec/bin/ossec-syscheckd
    276 ?        Sl     0:00 /var/ossec/bin/ossec-remoted
    313 ?        Sl     0:00 /var/ossec/bin/ossec-logcollector
    333 ?        Sl     0:00 /var/ossec/bin/ossec-monitord
    375 ?        Sl     0:00 /var/ossec/bin/wazuh-modulesd
    619 ?        Sl     0:00 node /var/ossec/api/app.js
```

We identify `619` as the Wazuh API process, which uses node (deprecated in 4.0.0).
If you install the Wazuh manager 4.0, the installation goes well and the output is the following:
```
Installed:
  wazuh-manager.x86_64 0:4.0.0-1                                                                                                                                                                                                

Replaced:
  wazuh-api.x86_64 0:3.13.1-1                                                                                                                                                                                                   

Complete!
[root@f12cb82846a7 /]# ps -xa | grep ossec
    543 ?        Sl     0:00 node /var/ossec/api/app.js
   1310 ?        Sl     0:00 /var/ossec/bin/ossec-authd
   1326 ?        Sl     0:00 /var/ossec/bin/wazuh-db
   1350 ?        Sl     0:00 /var/ossec/bin/ossec-execd
   1362 ?        Sl     0:00 /var/ossec/bin/ossec-analysisd
   1457 ?        SNl    0:04 /var/ossec/bin/ossec-syscheckd
   1469 ?        Sl     0:00 /var/ossec/bin/ossec-remoted
   1502 ?        Sl     0:00 /var/ossec/bin/ossec-logcollector
   1546 ?        Sl     0:00 /var/ossec/bin/ossec-monitord
   1558 ?        Sl     0:00 /var/ossec/bin/wazuh-modulesd
   2096 pts/0    S+     0:00 grep --color=auto ossec
``` 
We can see the node API in 4.0.0. If we remove the Wazuh manager and we check the processes:
```
[root@f12cb82846a7 /]# ps -xa | grep ossec
    543 ?        Sl     0:00 node /var/ossec/api/app.js
   2390 pts/0    S+     0:00 grep --color=auto ossec
```

The node Wazuh API process still there. Tested in a docker CentOS 7 image. 

Regards, 
Alberto R

**Comment by AdriiiPRodri** [comment]
## Status update

Hi team,

We have been investigating this error and have come to the conclusion that the error occurs because of the version of the Nodejs installed on the system (**8.17**). So far we have tried this process with Node 10 (**10.22**) and the error does not occur, everything is installed correctly and API 3.X is stopped. Here we can see the output in this case:

```
Installed:
  wazuh-manager.x86_64 0:4.0.0-1

Replaced:
  wazuh-api.x86_64 0:3.13.1-1

Complete!
[root@d5b2b6ff61d8 /]# ps -xa | grep ossec
 3371 ?        Sl     0:00 /var/ossec/bin/ossec-authd
 3387 ?        Sl     0:00 /var/ossec/bin/wazuh-db
 3411 ?        Sl     0:00 /var/ossec/bin/ossec-execd
 3423 ?        Sl     0:00 /var/ossec/bin/ossec-analysisd
 3518 ?        SNl    0:04 /var/ossec/bin/ossec-syscheckd
 3530 ?        Sl     0:00 /var/ossec/bin/ossec-remoted
 3563 ?        Sl     0:00 /var/ossec/bin/ossec-logcollector
 3579 ?        Sl     0:00 /var/ossec/bin/ossec-monitord
 3589 ?        Sl     0:00 /var/ossec/bin/wazuh-modulesd
 4033 ?        Sl     0:08 /var/ossec/framework/python/bin/python3 /var/ossec/api/scripts/wazuh-apid.py restart
 4118 pts/0    S+     0:00 grep --color=auto ossec
```

One possible solution to this error is to ensure that the API process is correctly stopped and if it is not, kill the process. This would cover all combinations of Nodejs and Wazuh API versions. However, it is possible that there is a better solution, we have to investigate this and modify the package generators.

API not stopped: Nodejs: **8.17.0**, Wazuh-API: **3.13.1**, Wazuh-manager: **3.13.1**, Wazuh-manager: **4.0.0**
API stopped: Nodejs: **10.22.0**, Wazuh-API: **3.13.1**, Wazuh-manager: **3.13.1**, Wazuh-manager: **4.0.0**

### ToDo

- [ ] Check the upgrade to 4.0 with Node 4.X (>= 4.6.1) and Wazuh 3.X
- [ ] Check the upgrade to 4.0 with Node 5.X and Wazuh 3.X
- [ ] Check the upgrade to 4.0 with Node 6.X and Wazuh 3.X
- [ ] Check the upgrade to 4.0 with Node 7.X and Wazuh 3.X
- [ ] Check the upgrade to 4.0 with Node 8.X and Wazuh 3.X
- [ ] Check the upgrade to 4.0 with Node 9.X and Wazuh 3.X

Regards

**Comment by CarlosRS9** [comment]
## Status Update

We have been investigating this error and the conclusion is that this error only happens on CentOS environments when updating from packages because the RPM spec file was missing the additional step we added to the DEB spec file. With this change we make sure the old api node process is stopped before updating. We have opened the following PR to add that missing part to the spec file: https://github.com/wazuh/wazuh-packages/pull/464

We have performed several tests and with this change applied the old api node process is killed as expected.

Regarding the problem detected by Adrián, this is fixed in the following PR: https://github.com/wazuh/wazuh/pull/5679

Best regards.
